//
// Created by matth on 11/13/2019.
//

#ifndef MOTEURDEJEUX_SRC_GAMEFRAMEWORK_COMPONENTS_MESHRENDERER_HPP
#define MOTEURDEJEUX_SRC_GAMEFRAMEWORK_COMPONENTS_MESHRENDERER_HPP


class MeshRenderer {

};


#endif //MOTEURDEJEUX_SRC_GAMEFRAMEWORK_COMPONENTS_MESHRENDERER_HPP
