#ifndef MOTEUR_DE_JEUX_SRC_ENGINE_ASSETS_ASSETS_TYPES_HPP
#define MOTEUR_DE_JEUX_SRC_ENGINE_ASSETS_ASSETS_TYPES_HPP

#include <Engine/Core/BasicTypes.hpp>
#include "AssetManager.hpp"

#endif  /* !MOTEUR_DE_JEUX_SRC_ENGINE_ASSETS_ASSETS_TYPES_HPP */
