#ifndef MOTEUR_DE_JEUX_ENGINE_GAME_FRAMEWORK_FORWARD_HPP
#define MOTEUR_DE_JEUX_ENGINE_GAME_FRAMEWORK_FORWARD_HPP

class Component;
class Transform;
class GameObject;

#endif  /* !MOTEUR_DE_JEUX_ENGINE_GAME_FRAMEWORK_FORWARD_HPP */
