#ifndef MOTEUR_DE_JEUX_SRC_ENGINE_GAME_FRAMEWORK_MANAGERS_HPP
#define MOTEUR_DE_JEUX_SRC_ENGINE_GAME_FRAMEWORK_MANAGERS_HPP

#include "Managers/SceneManager.hpp"
#include "Managers/ComponentManager.hpp"

#endif  /* !MOTEUR_DE_JEUX_SRC_ENGINE_GAME_FRAMEWORK_MANAGERS_HPP */
