#ifndef MOTEUR_DE_JEUX_SRC_ENGINE_CORE_PUBLIC_NAME_GENERATOR_HPP
#define MOTEUR_DE_JEUX_SRC_ENGINE_CORE_PUBLIC_NAME_GENERATOR_HPP


class NameGenerator {

};


#endif  /* !MOTEUR_DE_JEUX_SRC_ENGINE_CORE_PUBLIC_NAME_GENERATOR_HPP */
